export enum LogTags {
  DEFAULT = 'DEV MODE MESSAGE',
  DEPRECATED = 'DEPRECATED',
  INCOMPATIBLE = 'INCOMPATIBLE',
  INFO = 'INFO',
  DEBUG = 'DEBUG',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
}

export const DEFAULT_LABEL_COLOR = '#1E90FF';